[workspace]
members = [
    "light-letter",
    "light-letter-rpc",
    "light-letter-web",
    "light-letter-i18n",
    "light-letter-backstage",
    "light-letter-theme-ivy-leaf",
]

[profile.release]
opt-level = "s"
