[resource]
web = "./light-letter-web"
themes = { light-letter-theme-ivy-leaf = "./light-letter-theme-ivy-leaf" }

[net]
ip = "127.0.0.1"
port = [2180, 2280]

[db]
username = "light_letter"
password = "light_letter"

[[site]]
name = "local-1"
database = "light_letter_local_1"
type = "blog"
host = "localhost:2180"
theme = "light-letter-theme-ivy-leaf"

[[site]]
name = "local-2"
type = "static"
database = "light_letter_local_2"
host = "127.0.0.1:2180"
alias = ["127.0.0.1:2280"]
